Home Work 11
Otus-DevOps-2022-02/krang404_infra pull request #11
Opened 2022-05-07 10:21 UTC by krang404

# Выполнено ДЗ № 11

 - [выполнено] Основное ДЗ
 - [ не выполнено ] Задание со *

## В процессе сделано:
 - Создан Vagrantfile для провиженинга вируальных машин Virtualbox (создаются appserver и dbserver).
 - Дополнительно в провиженинг appserver добавлены глобальные переменные для проброса порта 9292 на 80 порт через прокси.
 - Для тестирования роли db создано виртуальное окружение с помощью virtualenv, в которое помещены инструменты согласно /ansible/requirements.txt. Инстанс для тестирования создается molecule на базе vagrant, провиженинг осуществляется Asible, тестирование запущенного сервиса MongoDB - с помощью testinfra. Тестируется состояние сервиса mongodb (запущен, или нет, а также включен, или нет), тестируется конфигурация MongoDB (наличие файла mongod.conf, а также присутствие строки 'bindIp: 0.0.0.0' в конфиге). Кроме того, дополнительно написаны проверки на прослушивание порта 27017: проверка осуществляется с использовнием двух модулей Testinfra (socket и addr). Проверяется два сокета (tcp:27017 и /tmp/mongodb-27017.sock), а также доступность порта 27017.
 - В провиженинг Packer включены роли app и db.

## Как запустить проект:
 - Для запуска двух серверов в директории ansible выполнить vagrant up
 - Для тестирования роли в директории ansible/roles/db активировать виртуальное окружение и выполнить molecule test 

## Как проверить работоспособность:
 - Перейти на 10.10.10.20

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2022-05-07 10:36 UTC, krang404 commented
Я, похоже, сломал автотесты. Workflow нормально провалидировало мою ветку, но в мердж-реквест это не попало.

2022-05-10 10:20 UTC, mrgreyves requested changes
Здравствуйте!)
Ну да, немного подломили их =)
Сломались они потому что были, видимо, случайно удалены
Просто закомитьте их обратно =)

2022-05-11 10:50 UTC, krang404 commented
Тесты вернулись на место

2022-05-12 08:54 UTC, mrgreyves approved these changes
Здравствуйте!)
Вот теперь все круто =)

2022-05-12 09:34 UTC, merged